# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-25 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0004_auto_20191022_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='link',
            field=models.URLField(db_index=True, max_length=150, null=True, unique=True),
        ),
    ]
